In [69]:
import numpy as np
from pprint import pprint

### <b> Task №1

In [53]:
def kramer(a, b):    
    assert a.shape[0] == a.shape[1], 'Non square matrix'
    
    det_a = round(np.linalg.det(a), 4)
    assert det_a != 0, 'Singular matrix'
    
    
    det_array = np.array([0 for _ in range(len(a))])
    res_array = np.array([0 for _ in range(len(a))])
    
    for i in range(len(a)):
        tmp_matrix = a.copy()
        tmp_matrix[:, i] = b
        det_array[i] = round(np.linalg.det(tmp_matrix), 4)
        res_array[i] = det_array[i]/det_a
    
    return res_array

__а)__ $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [61]:
a = np.array([[1, -2],
              [3, -4]])
b = np.array([1, 7])

print(a@kramer(a, b))

[1 7]


__б)__ $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [62]:
a = np.array([[2, -1, 5],
              [1, 1, -3],
              [2, 4, 1]])

b = np.array([10, -2, 1])

print(a@kramer(a,b))

[10 -2  1]


### <b> Task №2

In [89]:
def plu(a):    
    n = a.shape[0]  
    
    P = np.eye(n).astype('float32') #permutation matrix
    L = np.eye(n).astype('float32')
    U = a.copy().astype('float32')
    
    for i in range(n):
        
        #swaping rows if needed   
        for k in range(i, n): 
            if not np.isclose(U[i, i], 0.0):
                break
            U[[k, k+1]] = U[[k+1, k]]
            P[[k, k+1]] = P[[k+1, k]]
            
        #elimination
        eliminator = U[i+1:, i] / U[i, i]
        L[i+1:, i] = eliminator
        U[i+1:] -= eliminator[:, np.newaxis] * U[i]
        
    return P, L, U

__а)__$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

In [88]:
a = np.array([[1, 2, 4], 
              [2, 9, 12],
              [3, 26, 30]])

P, L, U = plu(a)
pprint(L)


array([[1., 0., 0.],
       [2., 1., 0.],
       [3., 4., 1.]], dtype=float32)


In [90]:
pprint(L@U)

array([[ 1.,  2.,  4.],
       [ 2.,  9., 12.],
       [ 3., 26., 30.]], dtype=float32)


   __б)__$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

In [91]:
a = np.array([[1, 1, 2, 4],
              [2, 5, 8, 9],
              [3, 18, 29,18],
              [4, 22, 53, 33]            
             ])

P, L, U = plu(a)
pprint(L)

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [3., 5., 1., 0.],
       [4., 6., 7., 1.]], dtype=float32)


In [92]:
pprint(L@U)

array([[ 1.,  1.,  2.,  4.],
       [ 2.,  5.,  8.,  9.],
       [ 3., 18., 29., 18.],
       [ 4., 22., 53., 33.]], dtype=float32)


### <b> Task №3

In [93]:
def straight_lu(L, b):    
    n = L.shape[0]
    
    y = np.zeros_like(b)
    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

In [94]:
def reverse_lu(U, y):
    n = U.shape[0]
    
    x = np.zeros_like(y)
    x[-1] = y[-1] / U[-1, -1]
    
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x


In [103]:
def plu_solver(a, b):
    
    P, L, U = plu(a)
    
    y = straight_lu(L, P@b)
    
    return np.round(reverse_lu(U, y), 4)

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [107]:
a = np.array([[2, 1, 3],
              [11, 7, 5],
              [9, 8, 4]            
             ])

b = np.array([1, -6, -5])

print(f'Решение методом LU-разложения: {plu_solver(a, b)}')
print(f'Решение методом Крамера: {kramer(a, b)}')

Решение методом LU-разложения: [-1.  0.  1.]
Решение методом Крамера: [-1  0  1]


### <b> Task №4

In [130]:
def cholesky_solver(a, b):
    
    L = np.linalg.cholesky(a)
    
    y = straight_lu(L, b)
    
    return np.round(reverse_lu(L.T, y), 4)
    
    

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [128]:
a = np.array([[81, -45, 45],
              [-45, 50, -15],
              [45, -15, 38]             
             ])

b = np.array([531, -460, 193])

In [132]:
print(f'Решение методом Холецкого: {cholesky_solver(a, b)}')
print(f'Решение методом LU-разложения: {plu_solver(a, b)}')
print(f'Решение методом Крамера: {kramer(a, b)}')

Решение методом Холецкого: [ 6 -5 -4]
Решение методом LU-разложения: [ 6. -5. -4.]
Решение методом Крамера: [ 6 -5 -4]
