In [1]:
import numpy as np

### <b> Task №1
    

* а) AB, BA - нет
* б) AB - да, BA - нет. AB = $[2 x 3]$
* в) AB, BA - да. AB = $[8 x 8]$, BA = $[3 x 3]$
* г) AB, BA - да. AB = BA = $[4 x 4]$

### <b> Task №2

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Sum of matrices:\n{A+B}')
print(f'Multiplication of matrices:\n{A@B}')

Sum of matrices:
[[ 5 -3]
 [ 3  5]]
Multiplication of matrices:
[[  4 -11]
 [ 12  -3]]


### <b> Task №3

In [7]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(3*A - 2*B + 4*C)

[[ 11  -5]
 [  9 -12]]


### <b> Task №4

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A * A_T:\n{A@A.T}')
print(f'A_T * A:\n{A.T@A}')

A * A_T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A_T * A:
[[45  0]
 [ 0 14]]


### <b> Task №5

In [30]:
def mult(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    assert a_cols == b_rows, 'multiplication does not exist'
    AB = [[0 for _ in range(b_cols)] for __ in range(a_rows)]
    for i in range(a_rows):
        for j in range(b_cols):
            for k in range(a_cols):
                AB[i][j] += A[i][k] * B[k][j]
    return AB